---
title: "test"
output: html_document
date: "2023-04-14"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(DoE.base)
library(ggcorrplot)
library(plotly)
```

```{r}
test <- fac.design( nlevels = c(3,3,3))
show.oas(nlevels =c(3,3,3), regular = "all", GRgt3 = "all", Rgt3 = FALSE)
res <- oa.design(L9.3.4, nlevels = c(3,3,3), columns = "min3")
#test <- FrF2(nfactors = 5,  resolution = 3, replications = 1)
test <- custom_corr_plot(res)
#test <- invisible(corrPlot(test))
test <- as.data.frame(test)
test <- rownames_to_column(test)
test <- pivot_longer(test, cols = !rowname, names_to = "variables", values_to = "correlation")
test <- mutate(test, correlation = round(correlation,2))

  tmp <- ggplot(test, aes(x = as.factor(rowname), y = as.factor(variables), fill = correlation)) +
    geom_tile(color = "white", lwd = 1, linetype = 1) +
    geom_text(family = "Arial", size = 5, aes(label = correlation, color = after_scale(prismatic::best_contrast(fill, c("white", "black"))))) +
    scale_fill_viridis(option = "C", discrete = FALSE, direction = -1, name = "Correlation") +
    labs(x = "Variables", y = "Variables") +
    # coord_fixed() +
    theme_bw() +
    theme(
      axis.title = element_text(color = "black", size = 16, family = "Arial", face = "bold"),
      axis.text = element_text(color = "black", size = 16, family = "Arial"),
      legend.title = element_text(color = "black", size = 16, family = "Arial", face = "bold")
    ) +
    theme(strip.text = element_text(family = "Arial", face = "bold", size = 16))
```

```{r}
  # Create CorrPlot
  cor_plot <- NULL
  # cor_plot <- try(custom_corr_plot(res, main.only = FALSE, three = FALSE))
  # 
  # if (inherits(res, "try-error")) {
  #   cor_plot <- NULL
  # } else {
  #   cor_plot <- as.data.frame(cor_plot)
  #   cor_plot <- rownames_to_column(cor_plot)
  #   cor_plot <- pivot_longer(cor_plot, cols = !rowname, names_to = "variables", values_to = "correlation")
  #   cor_plot <- cor_plot |> 
  #     mutate(rowname = str_sub(rowname, end = -2)) |> 
  #     mutate(variables = str_sub(variables, end = -2))
  #   
  #   str_sub(cor_plot$rowname, 6, 6) <- ""
  #   str_sub(cor_plot$variables , 6, 6) <- ""
  # }

  cor_plot <- try(custom_corr_plot(res, main.only = FALSE, three = FALSE))
  
  if (inherits(res, "try-error")) {
    cor_plot <- NULL
  } else {
    cor_plot <- as.data.frame(cor_plot)
    cor_plot <- rownames_to_column(cor_plot)
    cor_plot <- pivot_longer(cor_plot, cols = !rowname, names_to = "variables", values_to = "correlation")
    cor_plot <- cor_plot |> 
      mutate(rowname = str_sub(rowname, end = -2)) |> 
      mutate(variables = str_sub(variables, end = -2))
    
    str_sub(cor_plot$rowname, 6, 6) <- ""
    str_sub(cor_plot$variables , 6, 6) <- ""
  }
```

